"""
Author: Xander Peng
Date: 2024/8/1
Description: 
"""

''' Define the city clusters in 3 study areas '''
# China
JJJ = ["北京市",
       "天津市",
       "保定市", "唐山市", "石家庄市", '邢台市', "邯郸市", "秦皇岛市", "承德市", "廊坊市", "沧州市", "衡水市",
       "张家口市"]
CSJ = ["上海市",
       "南京市", "无锡市", "常州市", "苏州市", "南通市", '盐城市', '扬州市', '镇江市', '泰州市',
       "杭州市", "宁波市", "嘉兴市", "湖州市", "绍兴市", "金华市", "舟山市", "台州市",
       "合肥市", '芜湖市', '马鞍山', '铜陵市', '安庆市', '滁州市', '池州市', '宣城市']
ZSJ = ["广州市", "佛山市", "肇庆市",
       "深圳市", "东莞市", "惠州市",
       "珠海市", "中山市", "江门市", ]

NM = ['US.CT.HA',
      'US.CT.TO',
      'US.CT.WI',
      'US.CT.FA',
      'US.CT.MI',
      'US.CT.NH',
      'US.DE.NE',
      'US.DC.DI',
      'US.MD.CE',
      'US.MD.HA',
      'US.MD.CR',
      'US.MD.BA',
      'US.MD.FR',
      'US.MD.HO',
      'US.MD.MO',
      'US.MD.QU',
      'US.MD.AN',
      'US.MD.PR',
      'US.MD.CL',
      'US.MD.CH',
      'US.MA.ES',
      'US.MA.FR',
      'US.MA.MI',
      'US.MA.WO',
      'US.MA.HS',
      'US.MA.SU',
      'US.MA.HD',
      'US.MA.PL',
      'US.MA.NO',
      'US.MA.BR',
      'US.MA.BA',
      'US.NH.ST',
      'US.NH.RO',
      'US.NH.HI',
      'US.NJ.SU',
      'US.NJ.PA',
      'US.NJ.BE',
      'US.NJ.WA',
      'US.NJ.MR',
      'US.NJ.ES',
      'US.NJ.HD',
      'US.NJ.HN',
      'US.NJ.SO',
      'US.NJ.UN',
      'US.NJ.MI',
      'US.NJ.MN',
      'US.NJ.ME',
      'US.NJ.BU',
      'US.NJ.OC',
      'US.NJ.CM',
      'US.NJ.GL',
      'US.NJ.SA',
      'US.NJ.AT',
      'US.NY.PU',
      'US.NY.WE',
      'US.NY.RO',
      'US.NY.BN',
      'US.NY.NA',
      'US.NY.NE',
      'US.NY.QU',
      'US.NY.SF',
      'US.NY.KI',
      'US.NY.RI',
      'US.PA.PI',
      'US.PA.CB',
      'US.PA.NA',
      'US.PA.LH',
      'US.PA.BK',
      'US.PA.DA',
      'US.PA.PE',
      'US.PA.BC',
      'US.PA.MG',
      'US.PA.CU',
      'US.PA.LN',
      'US.PA.CH',
      'US.PA.YO',
      'US.PA.PH',
      'US.PA.DE',
      'US.RI.PR',
      'US.RI.BR',
      'US.RI.KE',
      'US.RI.NE',
      'US.RI.WA',
      'US.VA.LD',
      'US.VA.CK',
      'US.VA.FC',
      'US.VA.WR',
      'US.VA.FQ',
      'US.VA.PW',
      'US.VA.AR',
      'US.VA.FU',
      'US.VA.FC',
      'US.VA.RP',
      'US.VA.AX',
      'US.VA.MP',
      'US.VA.MS',
      'US.VA.CP',
      'US.VA.MD',
      'US.VA.SF',
      'US.VA.SP',
      'US.VA.FB',
      'US.WV.JE']

# BAY_AREA = ['US.CA.AA', 'US.CA.CN', 'US.CA.MN', 'US.CA.NA', 'US.CA.SF', 'US.CA.SM', 'US.CA.SC', 'US.CA.SO', 'US.CA.SL']
BAY_AREA = ["US.CA.AA",
            "US.CA.CN",
            "US.CA.MN",
            "US.CA.NA",
            "US.CA.SM",
            "US.CA.SL",
            "US.CA.SN",
            "US.CA.SO",
            "US.CA.SF"]

# Europe
WE = ["Belgium", "France", "Ireland", "Monaco", "Luxembourg", "Netherlands", "United Kingdom"]
NE = ["Denmark", "Finland", "Iceland", "Norway", "Sweden"]
